### PR TITLE
Adding change for boosted Wlv config and check for sys step

### PR DESCRIPTION
**Pull request by GLP90**

### CODE REVIEW

**Comment by piberger** [comment]
@GLP90 looks good can you please also remove the *.swp files, then I'll merge

**Comment by GLP90** [comment]
@piberger  they are all removed (the diff actually shows the removal of the bin files)

**Comment by perrozzi** [comment]
does cuts_BKP.ini need to be in?

**Comment by perrozzi** [comment]
as well as paths.ini.bkp

**Comment by GLP90** [comment]
no they are not needed. I removed them.

**Pull request merged**
