### PR TITLE
add check for prep output files copied to SE

### PR DESCRIPTION
**Pull request by perrozzi**

### CODE REVIEW

**Comment by piberger** [comment]
one could use the "isValidRootFile" function:
https://github.com/piberger/Xbb/blob/master/python/myutils/FileLocator.py#L96

**Comment by perrozzi** [comment]
done

**Comment by piberger** [comment]
getRemoteFileName is not necessary (outputFile should be already the full path when it is used in the .cp command). And looks like there is no exception thrown if file exists but is bad.

**Comment by perrozzi** [comment]
coding after drinking is not always a good idea :-D
should ok now

**Pull request merged**
